export const GET_PROJECT_LIST = 'GET_PROJECT_LIST';
export const GET_IMAGE_BASE_LIST = 'GET_IMAGE_BASE_LIST';
export const POST_BASE_CONFIG = 'POST_BASE_CONFIG';
export const POST_CREATE_MIRROR = 'POST_CREATE_MIRROR';
export const GET_MIRROR_LIST = 'GET_MIRROR_LIST';
export const GET_CONFIG_NETWORK_LIST = 'GET_CONFIG_NETWORK_LIST';
export const GET_CONFIG_ENV_LIST = 'GET_CONFIG_ENV_LIST';
export const POST_CONFIG_ENV_VARIABLE = 'POST_CONFIG_ENV_VARIABLE';
export const GET_CONFIG_RESOURCE_INFO = 'GET_CONFIG_RESOURCE_INFO';
export const GET_CONFIG_APPLY_DETAILS = 'GET_CONFIG_APPLY_DETAILS';
export const GET_CONFIG_APPLY_AUDITOR = 'GET_CONFIG_APPLY_AUDITOR';
export const POST_CONFIG_PUBLISH = 'POST_CONFIG_PUBLISH';
export const GET_APPLICATION_ASSOCIATIONS = 'GET_APPLICATION_ASSOCIATIONS';

export const SYNC_SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const SYNC_SET_ACTIVE_STEP = 'SYNC_SET_ACTIVE_STEP';
export const SYNC_SET_STEP_ACTIVE_PANEL_NAME = 'SYNC_SET_STEP_ACTIVE_PANEL_NAME';
export const SYNC_ACTIVE_NEXT_BTN = 'SYNC_ACTIVE_NEXT_BTN';
export const SYNC_DISABLE_NEXT_BTN = 'SYNC_DISABLE_NEXT_BTN';
export const SYNC_SET_SELECTED_BASE_IMAGED_ID = 'SYNC_SET_SELECTED_BASE_IMAGED_ID';
export const SYNC_INIT_STEP = 'SYNC_INIT_STEP';
export const SYNC_SHOW_DEPLOY_LOG = 'SYNC_SHOW_DEPLOY_LOG';

// 启动
export const GET_PROJECT_START = 'getProjectStart'
// 历史查询
export const GET_PROJECT_HISTORYLIST = 'getHistoryList'
// 实例数查询
export const GET_PROJECT_EXAMPLELIST = 'getExampleList'
// 版本切换
export const GET_PROJECT_CHANGEVERSION = 'changeVersion'
